/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppUser {
  alternative_id: Generated<string>;
  avatar_content_type: string | null;
  avatar_storage_key: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: string;
  name: string;
  password_hash: string;
}

export interface BoardColumn {
  created_at: Generated<Timestamp>;
  id: string;
  is_done: Generated<boolean>;
  name: string;
  position: number;
  project_id: string;
}

export interface Feedback {
  created_at: Generated<Timestamp>;
  id: string;
  message: string;
  page_path: string | null;
  user_id: string;
}

export interface Label {
  color: string;
  id: string;
  name: string;
  project_id: string;
}

export interface PersonalAccessToken {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: string;
  name: string;
  token_hash: string;
  user_id: string;
}

export interface Project {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  description: Generated<string>;
  id: string;
  is_public: Generated<boolean>;
  name: string;
}

export interface ProjectMember {
  created_at: Generated<Timestamp>;
  project_id: string;
  user_id: string;
}

export interface ProjectUserPosition {
  created_at: Generated<Timestamp>;
  position: number;
  project_id: string;
  user_id: string;
}

export interface ProjectWebhook {
  consecutive_failures: Generated<number>;
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
  id: string;
  project_id: string;
  secret: string;
  url: string;
}

export interface Session {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  token_hash: string;
  user_id: string;
}

export interface Task {
  archived_at: Timestamp | null;
  column_id: string;
  created_at: Generated<Timestamp>;
  description: Json | null;
  due_date: Timestamp | null;
  id: string;
  position: number;
  project_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface TaskActivity {
  actor_user_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  kind: string;
  new_value: Json | null;
  old_value: Json | null;
  seq: Generated<Int8>;
  task_id: string;
}

export interface TaskAssignee {
  task_id: string;
  user_id: string;
}

export interface TaskComment {
  body: Json;
  created_at: Generated<Timestamp>;
  id: string;
  task_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TaskDependency {
  blocked_task_id: string;
  blocker_task_id: string;
  created_at: Generated<Timestamp>;
}

export interface TaskImage {
  content_type: string;
  created_at: Generated<Timestamp>;
  filename: string;
  id: string;
  size_bytes: number;
  storage_key: string;
  task_id: string;
}

export interface TaskLabel {
  label_id: string;
  task_id: string;
}

export interface WebhookDelivery {
  attempt_count: Generated<number>;
  created_at: Generated<Timestamp>;
  event_type: string;
  id: string;
  last_attempt_at: Timestamp | null;
  last_error: string | null;
  last_status_code: number | null;
  next_attempt_at: Timestamp | null;
  payload: Json;
  redelivery_count: Generated<number>;
  status: Generated<string>;
  webhook_id: string;
}

export interface DB {
  app_user: AppUser;
  board_column: BoardColumn;
  feedback: Feedback;
  label: Label;
  personal_access_token: PersonalAccessToken;
  project: Project;
  project_member: ProjectMember;
  project_user_position: ProjectUserPosition;
  project_webhook: ProjectWebhook;
  session: Session;
  task: Task;
  task_activity: TaskActivity;
  task_assignee: TaskAssignee;
  task_comment: TaskComment;
  task_dependency: TaskDependency;
  task_image: TaskImage;
  task_label: TaskLabel;
  webhook_delivery: WebhookDelivery;
}
