/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppUser {
  alternative_id: Generated<string>;
  avatar_content_type: string | null;
  avatar_storage_key: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  email_verified_at: Timestamp | null;
  id: string;
  name: string;
  notify_added_to_project: Generated<boolean>;
  notify_bulk_task_assigned: Generated<boolean>;
  notify_task_assigned: Generated<boolean>;
  password_hash: string;
}

export interface BoardColumn {
  created_at: Generated<Timestamp>;
  id: string;
  is_done: Generated<boolean>;
  name: string;
  position: number;
  project_id: string;
}

export interface ChecklistItem {
  checked: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: string;
  position: number;
  task_id: string;
  text: string;
  updated_at: Generated<Timestamp>;
}

export interface Feedback {
  created_at: Generated<Timestamp>;
  id: string;
  message: string;
  page_path: string | null;
  user_id: string;
}

export interface Job {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: string;
  interval_seconds: number | null;
  kind: string;
  last_error: string | null;
  payload: Json;
  run_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface Label {
  color: string;
  id: string;
  name: string;
  project_id: string;
}

export interface PendingAssignmentNotification {
  actor_user_id: string;
  created_at: Generated<Timestamp>;
  project_id: string;
  recipient_user_id: string;
  task_id: string;
}

export interface PersonalAccessToken {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: string;
  name: string;
  token_hash: string;
  user_id: string;
}

export interface Project {
  archived_at: Timestamp | null;
  color: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  description: Generated<string>;
  id: string;
  is_public: Generated<boolean>;
  name: string;
}

export interface ProjectInvitation {
  created_at: Generated<Timestamp>;
  email: string;
  email_lower: Generated<string | null>;
  expires_at: Timestamp;
  id: string;
  invited_by: string;
  project_id: string;
  role: Generated<string>;
  token_hash: string;
}

export interface ProjectMember {
  created_at: Generated<Timestamp>;
  project_id: string;
  role: Generated<string>;
  user_id: string;
}

export interface ProjectUserPosition {
  created_at: Generated<Timestamp>;
  position: number;
  project_id: string;
  user_id: string;
}

export interface ProjectUserSeen {
  created_at: Generated<Timestamp>;
  last_seen_at: Generated<Timestamp>;
  project_id: string;
  user_id: string;
}

export interface ProjectWebhook {
  consecutive_failures: Generated<number>;
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
  id: string;
  project_id: string;
  secret: string;
  url: string;
}

export interface Session {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface Task {
  archived_at: Timestamp | null;
  column_id: string;
  column_since: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  description: Json | null;
  due_date: Timestamp | null;
  id: string;
  position: number;
  project_id: string;
  search_vector: Generated<string | null>;
  series_id: string | null;
  series_occurrence_date: Timestamp | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface TaskActivity {
  actor_user_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  kind: string;
  new_value: Json | null;
  old_value: Json | null;
  seq: Generated<Int8>;
  task_id: string;
}

export interface TaskAssignee {
  task_id: string;
  user_id: string;
}

export interface TaskAttachment {
  content_type: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  favicon_storage_key: string | null;
  filename: string | null;
  id: string;
  kind: string;
  preview_storage_key: string | null;
  size_bytes: number | null;
  storage_key: string | null;
  task_id: string;
  title: string | null;
  unfurl_state: string | null;
  updated_at: Generated<Timestamp>;
  url: string | null;
}

export interface TaskComment {
  body: Json;
  created_at: Generated<Timestamp>;
  id: string;
  task_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TaskDependency {
  blocked_task_id: string;
  blocker_task_id: string;
  created_at: Generated<Timestamp>;
}

export interface TaskImage {
  content_type: string;
  created_at: Generated<Timestamp>;
  filename: string;
  id: string;
  is_cover: Generated<boolean>;
  size_bytes: number;
  storage_key: string;
  task_id: string;
}

export interface TaskLabel {
  label_id: string;
  task_id: string;
}

export interface TaskSeries {
  column_id: string | null;
  consecutive_failures: Generated<number>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: Json | null;
  due_date: Timestamp | null;
  ended_at: Timestamp | null;
  id: string;
  last_error: string | null;
  last_missed_date: Timestamp | null;
  last_occurrence_date: Timestamp | null;
  missed_occurrence_count: Generated<number>;
  next_occurrence_at: Timestamp | null;
  next_occurrence_date: Timestamp | null;
  project_id: string;
  rrule: string;
  start_date: Timestamp;
  status: Generated<string>;
  timezone: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface TaskSeriesAssignee {
  series_id: string;
  user_id: string;
}

export interface TaskSeriesChecklistItem {
  id: string;
  position: number;
  series_id: string;
  text: string;
}

export interface TaskSeriesLabel {
  label_id: string;
  series_id: string;
}

export interface WebhookDelivery {
  attempt_count: Generated<number>;
  created_at: Generated<Timestamp>;
  event_type: string;
  id: string;
  last_attempt_at: Timestamp | null;
  last_error: string | null;
  last_status_code: number | null;
  next_attempt_at: Timestamp | null;
  payload: Json;
  redelivery_count: Generated<number>;
  status: Generated<string>;
  webhook_id: string;
}

export interface DB {
  app_user: AppUser;
  board_column: BoardColumn;
  checklist_item: ChecklistItem;
  feedback: Feedback;
  job: Job;
  label: Label;
  pending_assignment_notification: PendingAssignmentNotification;
  personal_access_token: PersonalAccessToken;
  project: Project;
  project_invitation: ProjectInvitation;
  project_member: ProjectMember;
  project_user_position: ProjectUserPosition;
  project_user_seen: ProjectUserSeen;
  project_webhook: ProjectWebhook;
  session: Session;
  task: Task;
  task_activity: TaskActivity;
  task_assignee: TaskAssignee;
  task_attachment: TaskAttachment;
  task_comment: TaskComment;
  task_dependency: TaskDependency;
  task_image: TaskImage;
  task_label: TaskLabel;
  task_series: TaskSeries;
  task_series_assignee: TaskSeriesAssignee;
  task_series_checklist_item: TaskSeriesChecklistItem;
  task_series_label: TaskSeriesLabel;
  webhook_delivery: WebhookDelivery;
}
