import { Client } from 'pg';
import { generateNKeysBetween, BASE_62_DIGITS } from 'fractional-indexing';
import { BOARD_TASK_CAP, type Scale } from './config';
import { benchDatabaseName } from './database';

const COLUMNS_PER_PROJECT = 6;
const LABELS_PER_PROJECT = 8;
// The last column is the done one, which is what my-tasks, the project list
// counts and the cross-project blocker counts all key off.
const DONE_COLUMN = COLUMNS_PER_PROJECT;

// One id space per table, so a uuid read out of a failing benchmark says which
// table it came from without a lookup.
const KIND = {
  user: 1,
  project: 2,
  column: 3,
  task: 4,
  label: 5,
  comment: 6,
  checklistItem: 7,
  activity: 8,
  session: 9,
} as const;

type Kind = keyof typeof KIND;

function benchUuid(kind: Kind, index: number): string {
  return `0000000${String(KIND[kind])}-0000-4000-8000-${index.toString(16).padStart(12, '0')}`;
}

function uuidSql(kind: Kind, expression: string): string {
  return `('0000000${String(KIND[kind])}-0000-4000-8000-' || lpad(to_hex((${expression})::bigint), 12, '0'))::uuid`;
}

export const BENCH_PASSWORD = 'bench-password-123';

function benchToken(userIndex: number): string {
  return `bench-session-token-${String(userIndex)}`;
}

// Reused across every scope rather than generated per column: a sort key only
// has to be unique within its own (group, sort_key) index, so one ordered run of
// valid keys serves every column in the instance. Generated by the real library
// so the keys the app later reads back as bounds are structurally valid — a
// hand-rolled string that merely sorts correctly makes the next appendKeys()
// throw.
function sortKeyRun(count: number): string[] {
  return generateNKeysBetween(null, null, count, BASE_62_DIGITS);
}

// Every title ends in "widget", so a search for it matches the whole instance —
// that is the pathological search case. The adjective matches ~5% of cards, and
// the ordinal makes each title unique for the single-hit case.
const TITLE_WORDS = [
  'alpha',
  'beta',
  'gamma',
  'delta',
  'epsilon',
  'zeta',
  'eta',
  'theta',
  'iota',
  'kappa',
  'lambda',
  'omicron',
  'sigma',
  'tau',
  'upsilon',
  'phi',
  'chi',
  'psi',
  'omega',
  'nu',
];

export const UNIVERSAL_SEARCH_TERM = 'widget';
export const SELECTIVE_SEARCH_TERM = TITLE_WORDS[0];

// 23 rather than 20: the title word cycles every 20 cards, so archiving on a
// multiple of 20 would archive every card carrying one particular word and
// quietly make that word return nothing.
const TITLE_SQL = `'Bench task ' || (n)::text || ' ' || (ARRAY[${TITLE_WORDS.map((w) => `'${w}'`).join(',')}])[1 + ((n) % ${String(TITLE_WORDS.length)})] || ' widget'`;

const DESCRIPTION_SQL = `
  case when (n) % 3 = 0 then jsonb_build_object(
    'type', 'doc',
    'content', jsonb_build_array(jsonb_build_object(
      'type', 'paragraph',
      'content', jsonb_build_array(jsonb_build_object(
        'type', 'text',
        'text', 'Description for bench task ' || (n)::text ||
                ' covering scope, risks, rollout and the widget it touches.'
      ))
    ))
  ) end`;

function tiptapDocSql(textExpression: string): string {
  return `jsonb_build_object(
    'type', 'doc',
    'content', jsonb_build_array(jsonb_build_object(
      'type', 'paragraph',
      'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', ${textExpression}))
    ))
  )`;
}

const PROJECT = {
  big: 1,
  oneColumn: 2,
  crowded: 3,
  public: 4,
  chain: 5,
  write: 6,
} as const;
const FIRST_ORDINARY_PROJECT = 7;

// The three read-worst-case boards sit exactly on the cap, so nothing can be
// created in them. Mutation scenarios get a board of their own, big enough that
// the per-write scans (the task-cap count, the sort-key probe) are doing real
// work and with room left for the iterations to land.
const WRITE_BOARD_HEADROOM = 1_000;

const USER = {
  hub: 1,
  loaded: 2,
  ordinary: 3,
  outsider: 4,
} as const;

interface Layout {
  bigTaskBase: number;
  oneColumnTaskBase: number;
  crowdedTaskBase: number;
  publicTaskBase: number;
  chainTaskBase: number;
  writeTaskBase: number;
  writeTaskCount: number;
  ordinaryTaskBase: number;
  ordinaryProjects: number;
  totalTasks: number;
}

function layout(scale: Scale): Layout {
  const bigTaskBase = 1;
  const oneColumnTaskBase = bigTaskBase + BOARD_TASK_CAP;
  const crowdedTaskBase = oneColumnTaskBase + BOARD_TASK_CAP;
  const publicTaskBase = crowdedTaskBase + scale.tasksPerProject;
  const chainTaskBase = publicTaskBase + BOARD_TASK_CAP;
  const writeTaskBase = chainTaskBase + scale.chainLength;
  const writeTaskCount = BOARD_TASK_CAP - WRITE_BOARD_HEADROOM;
  const ordinaryTaskBase = writeTaskBase + writeTaskCount;
  const ordinaryProjects = Math.max(scale.projects - FIRST_ORDINARY_PROJECT + 1, 0);
  return {
    bigTaskBase,
    oneColumnTaskBase,
    crowdedTaskBase,
    publicTaskBase,
    chainTaskBase,
    writeTaskBase,
    writeTaskCount,
    ordinaryTaskBase,
    ordinaryProjects,
    totalTasks: ordinaryTaskBase + ordinaryProjects * scale.tasksPerProject - 1,
  };
}

interface BenchActor {
  index: number;
  id: string;
  token: string;
}

/** Everything a scenario needs to address the seeded instance, all derived. */
export interface BenchIds {
  hubUser: BenchActor;
  loadedUser: BenchActor;
  ordinaryUser: BenchActor;
  outsider: BenchActor;
  bigProject: { id: string; columnIds: string[]; firstTaskId: string; lastTaskId: string };
  oneColumnProject: { id: string; columnId: string; firstTaskId: string };
  crowdedProject: { id: string };
  publicProject: { id: string };
  /** headTask is blocked by the whole chain; tailTask is its far upstream root. */
  chainProject: { id: string; headTaskId: string; tailTaskId: string };
  /** Carries the instance's comments, checklist rows, attachments and blockers. */
  hotTask: { id: string };
  /** Blocks a large fan-out, which is the other half of the my-tasks worst case. */
  blockingTask: { id: string };
  /** A near-cap board with room left, so mutations have somewhere to land. */
  writeProject: { id: string; columnIds: string[]; headroom: number; firstTaskId: string };
  ordinaryProject: { id: string };
  ordinaryTask: { id: string };
  totalTasks: number;
}

export function benchIds(scale: Scale): BenchIds {
  const l = layout(scale);
  const actor = (index: number): BenchActor => ({
    index,
    id: benchUuid('user', index),
    token: benchToken(index),
  });
  return {
    hubUser: actor(USER.hub),
    loadedUser: actor(USER.loaded),
    ordinaryUser: actor(USER.ordinary),
    outsider: actor(USER.outsider),
    bigProject: {
      id: benchUuid('project', PROJECT.big),
      columnIds: Array.from({ length: COLUMNS_PER_PROJECT }, (_, i) =>
        benchUuid('column', (PROJECT.big - 1) * COLUMNS_PER_PROJECT + i + 1)
      ),
      firstTaskId: benchUuid('task', l.bigTaskBase),
      lastTaskId: benchUuid('task', l.bigTaskBase + BOARD_TASK_CAP - 1),
    },
    oneColumnProject: {
      id: benchUuid('project', PROJECT.oneColumn),
      columnId: benchUuid('column', (PROJECT.oneColumn - 1) * COLUMNS_PER_PROJECT + 1),
      firstTaskId: benchUuid('task', l.oneColumnTaskBase),
    },
    crowdedProject: { id: benchUuid('project', PROJECT.crowded) },
    publicProject: { id: benchUuid('project', PROJECT.public) },
    chainProject: {
      id: benchUuid('project', PROJECT.chain),
      headTaskId: benchUuid('task', l.chainTaskBase),
      tailTaskId: benchUuid('task', l.chainTaskBase + scale.chainLength - 1),
    },
    hotTask: { id: benchUuid('task', l.bigTaskBase) },
    blockingTask: { id: benchUuid('task', l.bigTaskBase + BOARD_TASK_CAP - 1) },
    writeProject: {
      id: benchUuid('project', PROJECT.write),
      columnIds: Array.from({ length: COLUMNS_PER_PROJECT }, (_, i) =>
        benchUuid('column', (PROJECT.write - 1) * COLUMNS_PER_PROJECT + i + 1)
      ),
      headroom: WRITE_BOARD_HEADROOM,
      firstTaskId: benchUuid('task', l.writeTaskBase),
    },
    ordinaryProject: { id: benchUuid('project', FIRST_ORDINARY_PROJECT) },
    ordinaryTask: { id: benchUuid('task', l.ordinaryTaskBase) },
    totalTasks: l.totalTasks,
  };
}

export async function benchClient(): Promise<Client> {
  const client = new Client({
    host: process.env.DB_HOSTNAME || '127.0.0.1',
    port: Number(process.env.DB_PORT || 5432),
    user: process.env.DB_USER || 'postgres',
    password: process.env.DB_PASSWORD,
    database: benchDatabaseName(),
    // Bulk inserts of a few hundred thousand rows are exactly what the app
    // pool's 30s statement timeout exists to stop, so seeding takes a
    // connection of its own rather than the app's.
    statement_timeout: 0,
    connectionTimeoutMillis: 10_000,
  });
  await client.connect();
  return client;
}

export type SeedProgress = (step: string) => void;

export async function seed(
  scale: Scale,
  passwordHash: string,
  report: SeedProgress = () => {}
): Promise<BenchIds> {
  const client = await benchClient();
  const l = layout(scale);
  const keys = sortKeyRun(BOARD_TASK_CAP + 16);

  const run = async (step: string, sql: string, params: unknown[] = []): Promise<void> => {
    const started = performance.now();
    const result = await client.query(sql, params);
    const rows =
      typeof result.rowCount === 'number' ? ` ${result.rowCount.toLocaleString()} rows` : '';
    report(`${step}:${rows} ${(performance.now() - started).toFixed(0)}ms`);
  };

  try {
    // ---- accounts -------------------------------------------------------
    await run(
      'users',
      `insert into app_user (id, email, password_hash, name, email_verified_at, created_at)
       select ${uuidSql('user', 'n')},
              'bench-' || n::text || '@bench.example.com',
              $1,
              (ARRAY['Ash','Blake','Casey','Devin','Eden','Frankie','Gray','Harper'])[1 + (n % 8)]
                || ' Bench' || n::text,
              now(),
              now() - (n || ' minutes')::interval
       from generate_series(1, $2::int) n`,
      [passwordHash, scale.users]
    );

    await run(
      'sessions',
      `insert into session (id, user_id, token_hash, expires_at)
       select ${uuidSql('session', 'n')},
              ${uuidSql('user', 'n')},
              encode(sha256(convert_to('bench-session-token-' || n::text, 'utf8')), 'hex'),
              now() + interval '30 days'
       from generate_series(1, $1::int) n`,
      [scale.users]
    );

    // ---- projects, columns, labels --------------------------------------
    await run(
      'projects',
      `insert into project (id, name, description, created_by, is_public, color, created_at)
       select ${uuidSql('project', 'n')},
              'Bench Project ' || n::text,
              'A seeded project for benchmarking.',
              ${uuidSql('user', `case when n < ${String(FIRST_ORDINARY_PROJECT)} then ${String(USER.hub)} else 1 + ((n - 1) % $1::int) end`)},
              n = ${String(PROJECT.public)},
              (ARRAY['slate','rose','amber','emerald','sky','violet'])[1 + (n % 6)],
              now() - (n || ' minutes')::interval
       from generate_series(1, $2::int) n`,
      [scale.users, scale.projects]
    );

    await run(
      'columns',
      `insert into board_column (id, project_id, name, sort_key, is_done)
       select ${uuidSql('column', `(p - 1) * ${String(COLUMNS_PER_PROJECT)} + k`)},
              ${uuidSql('project', 'p')},
              'Column ' || k::text,
              ($1::text[])[k],
              k = ${String(DONE_COLUMN)}
       from generate_series(1, $2::int) p, generate_series(1, ${String(COLUMNS_PER_PROJECT)}) k`,
      [keys, scale.projects]
    );

    await run(
      'labels',
      `insert into label (id, project_id, name, color)
       select ${uuidSql('label', `(p - 1) * ${String(LABELS_PER_PROJECT)} + k`)},
              ${uuidSql('project', 'p')},
              'label-' || k::text,
              (ARRAY['#ef4444','#f97316','#eab308','#22c55e','#06b6d4','#3b82f6','#8b5cf6','#ec4899'])[k]
       from generate_series(1, $1::int) p, generate_series(1, ${String(LABELS_PER_PROJECT)}) k`,
      [scale.projects]
    );

    // ---- cards ----------------------------------------------------------
    // `columnCount` of 1 puts a whole capped board in one column, which is the
    // worst ordering case the product allows: every key competes in one scope.
    const taskInsert = (projectExpr: string, ordinalExpr: string, columnCount: number): string => {
      const columnSlot = `((n - 1) % ${String(columnCount)}) + 1`;
      const keySlot = `((n - 1) / ${String(columnCount)}) + 1`;
      return `insert into task (
                id, project_id, column_id, title, description, sort_key,
                created_at, updated_at, column_since, due_date, archived_at
              )
              select ${uuidSql('task', ordinalExpr)},
                     ${uuidSql('project', projectExpr)},
                     ${uuidSql('column', `(${projectExpr} - 1) * ${String(COLUMNS_PER_PROJECT)} + ${columnSlot}`)},
                     ${TITLE_SQL},
                     ${DESCRIPTION_SQL},
                     ($1::text[])[${keySlot}],
                     now() - (n || ' minutes')::interval,
                     now() - (n || ' minutes')::interval,
                     now() - (n || ' minutes')::interval,
                     case when n % 7 = 0 then (now() + ((n % 30) || ' days')::interval)::date end,
                     case when n % 23 = 0 then now() - interval '1 day' end`;
    };

    await run(
      `big board (${BOARD_TASK_CAP.toLocaleString()} cards)`,
      `${taskInsert(String(PROJECT.big), `${String(l.bigTaskBase)} - 1 + n`, COLUMNS_PER_PROJECT)}
       from generate_series(1, $2::int) n`,
      [keys, BOARD_TASK_CAP]
    );

    await run(
      `single-column board (${BOARD_TASK_CAP.toLocaleString()} cards)`,
      `${taskInsert(String(PROJECT.oneColumn), `${String(l.oneColumnTaskBase)} - 1 + n`, 1)}
       from generate_series(1, $2::int) n`,
      [keys, BOARD_TASK_CAP]
    );

    await run(
      'crowded board',
      `${taskInsert(String(PROJECT.crowded), `${String(l.crowdedTaskBase)} - 1 + n`, COLUMNS_PER_PROJECT)}
       from generate_series(1, $2::int) n`,
      [keys, scale.tasksPerProject]
    );

    await run(
      `public board (${BOARD_TASK_CAP.toLocaleString()} cards)`,
      `${taskInsert(String(PROJECT.public), `${String(l.publicTaskBase)} - 1 + n`, COLUMNS_PER_PROJECT)}
       from generate_series(1, $2::int) n`,
      [keys, BOARD_TASK_CAP]
    );

    await run(
      `dependency chain (${scale.chainLength.toLocaleString()} cards)`,
      `${taskInsert(String(PROJECT.chain), `${String(l.chainTaskBase)} - 1 + n`, COLUMNS_PER_PROJECT)}
       from generate_series(1, $2::int) n`,
      [keys, scale.chainLength]
    );

    await run(
      `write board (${l.writeTaskCount.toLocaleString()} cards, ${WRITE_BOARD_HEADROOM.toLocaleString()} spare)`,
      `${taskInsert(String(PROJECT.write), `${String(l.writeTaskBase)} - 1 + n`, COLUMNS_PER_PROJECT)}
       from generate_series(1, $2::int) n`,
      [keys, l.writeTaskCount]
    );

    if (l.ordinaryProjects > 0) {
      await run(
        `ordinary boards (${l.ordinaryProjects.toLocaleString()} projects)`,
        `${taskInsert('p', `${String(l.ordinaryTaskBase)} + (p - ${String(FIRST_ORDINARY_PROJECT)}) * ${String(scale.tasksPerProject)} + n - 1`, COLUMNS_PER_PROJECT)}
         from generate_series(${String(FIRST_ORDINARY_PROJECT)}, $2::int) p,
              generate_series(1, ${String(scale.tasksPerProject)}) n`,
        [keys, scale.projects]
      );
    }

    // ---- membership -----------------------------------------------------
    await run(
      `hub membership (${scale.hubProjects.toLocaleString()} projects)`,
      `insert into project_member (project_id, user_id, role, created_at)
       select ${uuidSql('project', 'p')}, ${uuidSql('user', String(USER.hub))},
              case when p % 4 = 0 then 'viewer' else 'editor' end,
              now() - (p || ' minutes')::interval
       from generate_series(${String(FIRST_ORDINARY_PROJECT)}, least($1::int, $2::int)) p
       on conflict do nothing`,
      [FIRST_ORDINARY_PROJECT + scale.hubProjects - 1, scale.projects]
    );

    // The loaded user reads everywhere their assignments land, so my-tasks sees
    // every one of them rather than filtering most away as unreadable.
    await run(
      'loaded-user membership',
      `insert into project_member (project_id, user_id, role, created_at)
       select ${uuidSql('project', 'p')}, ${uuidSql('user', String(USER.loaded))}, 'editor', now()
       from generate_series(1, $1::int) p
       on conflict do nothing`,
      [scale.projects]
    );

    await run(
      `crowded project (${scale.crowdedMembers.toLocaleString()} members)`,
      `insert into project_member (project_id, user_id, role, created_at)
       select ${uuidSql('project', String(PROJECT.crowded))}, ${uuidSql('user', 'n')},
              case when n % 3 = 0 then 'viewer' else 'editor' end,
              now() - (n || ' seconds')::interval
       from generate_series(1, least($1::int, $2::int)) n
       on conflict do nothing`,
      [scale.crowdedMembers, scale.users]
    );

    // Ordinary sharing, skipping the outsider so the 404 paths stay 404.
    await run(
      'scattered membership',
      `insert into project_member (project_id, user_id, role, created_at)
       select ${uuidSql('project', 'p')}, ${uuidSql('user', '1 + ((p::bigint * 7 + k * 13) % $1::int)')},
              'editor', now()
       from generate_series(1, $2::int) p, generate_series(1, 4) k
       where 1 + ((p::bigint * 7 + k * 13) % $1::int) <> ${String(USER.outsider)}
       on conflict do nothing`,
      [scale.users, scale.projects]
    );

    await run(
      'personal project order',
      `insert into project_user_position (project_id, user_id, sort_key, created_at)
       select ${uuidSql('project', 'p')}, ${uuidSql('user', String(USER.hub))}, ($1::text[])[p], now()
       from generate_series(1, least($2::int, ${String(BOARD_TASK_CAP)})) p
       on conflict do nothing`,
      [keys, scale.projects]
    );

    // Half the hub user's boards have been opened and half never have: the
    // unseen-changes dot takes a different path for each.
    await run(
      'seen markers',
      `insert into project_user_seen (project_id, user_id, last_seen_at, created_at)
       select ${uuidSql('project', 'p')}, ${uuidSql('user', String(USER.hub))},
              now() - interval '2 days', now() - interval '2 days'
       from generate_series(1, $1::int) p
       where p % 2 = 0
       on conflict do nothing`,
      [scale.projects]
    );

    // ---- assignees and labels on cards ----------------------------------
    await run(
      `loaded-user assignments (${scale.loadedUserTasks.toLocaleString()})`,
      `insert into task_assignee (task_id, user_id)
       select t.id, ${uuidSql('user', String(USER.loaded))}
       from (
         select task.id
         from task
         join board_column on board_column.id = task.column_id
         where board_column.is_done = false and task.archived_at is null
         order by task.id
         limit $1::int
       ) t
       on conflict do nothing`,
      [scale.loadedUserTasks]
    );

    await run(
      'scattered assignments',
      `insert into task_assignee (task_id, user_id)
       select ${uuidSql('task', 'n')}, ${uuidSql('user', '1 + ((n::bigint * 31 + k * 17) % $1::int)')}
       from generate_series(1, $2::int) n, generate_series(1, 2) k
       where n % 2 = 0
       on conflict do nothing`,
      [scale.users, l.totalTasks]
    );

    // Joined rather than computed from ordinals: the label has to belong to the
    // card's own project, and the join is the only thing that cannot drift from
    // however the cards were laid out above.
    await run(
      'labels on cards',
      `insert into task_label (task_id, label_id)
       select task.id, label.id
       from task
       join label on label.project_id = task.project_id
       where (('x' || substr(md5(task.id::text || label.id::text), 1, 8))::bit(32)::bigint) % 6 = 0
       on conflict do nothing`
    );

    // ---- dependency edges -----------------------------------------------
    // Every edge points from a higher card ordinal to a lower one, which makes
    // the whole seeded graph acyclic by construction. A seeded cycle is not
    // reachable through the API, so benchmarking the cycle check against one
    // would measure a state production can never be in.
    await run(
      `dependency chain edges (${scale.chainLength.toLocaleString()} deep)`,
      `insert into task_dependency (blocker_task_id, blocked_task_id)
       select ${uuidSql('task', `${String(l.chainTaskBase)} + n`)},
              ${uuidSql('task', `${String(l.chainTaskBase)} + n - 1`)}
       from generate_series(1, $1::int - 1) n
       on conflict do nothing`,
      [scale.chainLength]
    );

    // Half in the hot card's own project (which the board payload renders as
    // blocker_ids) and half from another one (which becomes the cross-project
    // blocker count).
    await run(
      `hot card blockers (${scale.hotTaskEdges.toLocaleString()})`,
      `insert into task_dependency (blocker_task_id, blocked_task_id)
       select case when n % 2 = 0
                then ${uuidSql('task', `${String(l.bigTaskBase)} + n`)}
                else ${uuidSql('task', `${String(l.oneColumnTaskBase)} + n`)}
              end,
              ${uuidSql('task', String(l.bigTaskBase))}
       from generate_series(1, $1::int) n
       on conflict do nothing`,
      [scale.hotTaskEdges]
    );

    await run(
      `blocking card dependents (${scale.hotTaskEdges.toLocaleString()})`,
      `insert into task_dependency (blocker_task_id, blocked_task_id)
       select ${uuidSql('task', `${String(l.bigTaskBase)} + ${String(BOARD_TASK_CAP)} - 1`)},
              ${uuidSql('task', `${String(l.bigTaskBase)} + n`)}
       from generate_series(1, least($1::int, ${String(BOARD_TASK_CAP)} - 2)) n
       on conflict do nothing`,
      [scale.hotTaskEdges]
    );

    // The ±500 window regularly crosses a project boundary, so a good share of
    // these land cross-project without having to be aimed there.
    await run(
      `scattered dependency edges (${scale.scatteredEdges.toLocaleString()})`,
      `insert into task_dependency (blocker_task_id, blocked_task_id)
       select ${uuidSql('task', 'b.blocked + 1 + ((j::bigint * 97) % 500)')}, ${uuidSql('task', 'b.blocked')}
       from generate_series(1, $1::int) j,
            lateral (select 1 + ((j::bigint * 7919) % ($2::int - 501)) as blocked) b
       on conflict do nothing`,
      [scale.scatteredEdges, l.totalTasks]
    );

    // ---- comments, checklists, activity ---------------------------------
    await run(
      `scattered comments (${scale.scatteredComments.toLocaleString()})`,
      `insert into task_comment (id, task_id, user_id, body, created_at, updated_at)
       select ${uuidSql('comment', 'j')},
              ${uuidSql('task', '1 + ((j::bigint * 7919) % $2::int)')},
              ${uuidSql('user', '1 + ((j::bigint * 31) % $3::int)')},
              ${tiptapDocSql(`'Bench comment ' || j::text || ' on the widget.'`)},
              now() - ((j % 5000) || ' minutes')::interval,
              now() - ((j % 5000) || ' minutes')::interval
       from generate_series(1, $1::int) j
       on conflict do nothing`,
      [scale.scatteredComments, l.totalTasks, scale.users]
    );

    const hotCommentBase = scale.scatteredComments + 1;
    await run(
      `hot card comments (${scale.hotTaskComments.toLocaleString()})`,
      `insert into task_comment (id, task_id, user_id, body, created_at, updated_at)
       select ${uuidSql('comment', `${String(hotCommentBase)} + j`)},
              ${uuidSql('task', String(l.bigTaskBase))},
              ${uuidSql('user', '1 + (j % $2::int)')},
              ${tiptapDocSql(`'Hot card comment ' || j::text`)},
              now() - (j || ' minutes')::interval,
              now() - (j || ' minutes')::interval
       from generate_series(1, $1::int) j
       on conflict do nothing`,
      [scale.hotTaskComments, scale.users]
    );

    // The public board serves every comment on every published card in one
    // response, so the capped public project carries one per card: that is the
    // largest public payload the product can produce.
    const publicCommentBase = hotCommentBase + scale.hotTaskComments + 1;
    await run(
      `public board comments (${BOARD_TASK_CAP.toLocaleString()})`,
      `insert into task_comment (id, task_id, user_id, body, created_at, updated_at)
       select ${uuidSql('comment', `${String(publicCommentBase)} + n`)},
              ${uuidSql('task', `${String(l.publicTaskBase)} - 1 + n`)},
              ${uuidSql('user', '1 + (n % $2::int)')},
              ${tiptapDocSql(`'Public board comment ' || n::text`)},
              now() - (n || ' minutes')::interval,
              now() - (n || ' minutes')::interval
       from generate_series(1, $1::int) n
       on conflict do nothing`,
      [BOARD_TASK_CAP, scale.users]
    );

    await run(
      `hot card checklist (${scale.hotTaskChecklistItems.toLocaleString()})`,
      `insert into checklist_item (id, task_id, text, checked, sort_key, created_at, updated_at)
       select ${uuidSql('checklistItem', 'j')},
              ${uuidSql('task', String(l.bigTaskBase))},
              'Hot checklist step ' || j::text,
              j % 3 = 0,
              ($1::text[])[j],
              now(), now()
       from generate_series(1, $2::int) j
       on conflict do nothing`,
      [keys, scale.hotTaskChecklistItems]
    );

    const publicChecklistBase = scale.hotTaskChecklistItems + 1;
    await run(
      `public board checklist (${(BOARD_TASK_CAP * 2).toLocaleString()})`,
      `insert into checklist_item (id, task_id, text, checked, sort_key, created_at, updated_at)
       select ${uuidSql('checklistItem', `${String(publicChecklistBase)} + (n - 1) * 2 + k`)},
              ${uuidSql('task', `${String(l.publicTaskBase)} - 1 + n`)},
              'Public step ' || k::text,
              k = 1,
              ($1::text[])[k],
              now(), now()
       from generate_series(1, $2::int) n, generate_series(1, 2) k
       on conflict do nothing`,
      [keys, BOARD_TASK_CAP]
    );

    // Half of these are by the hub user and half are not, which is what decides
    // whether the project list's unseen dot can short-circuit.
    await run(
      `activity (${scale.scatteredActivity.toLocaleString()})`,
      `insert into task_activity (id, task_id, actor_user_id, kind, new_value, created_at)
       select ${uuidSql('activity', 'j')},
              ${uuidSql('task', '1 + ((j::bigint * 104729) % $2::int)')},
              ${uuidSql('user', '1 + ((j::bigint * 13) % $3::int)')},
              (ARRAY['created','title_changed','column_changed','assignee_added','label_added'])[1 + (j % 5)],
              jsonb_build_object('text', 'bench'),
              now() - ((j % 4000) || ' minutes')::interval
       from generate_series(1, $1::int) j
       on conflict do nothing`,
      [scale.scatteredActivity, l.totalTasks, scale.users]
    );

    // ---- attachments ----------------------------------------------------
    // One cover per card on a tenth of the instance: the board payload runs a
    // correlated cover lookup per card whether or not one exists.
    await run(
      'cover images',
      `insert into task_attachment (
         id, task_id, kind, filename, size_bytes, image_storage_key, image_content_type,
         is_cover, created_at, updated_at
       )
       select gen_random_uuid(),
              ${uuidSql('task', 'n * 10')},
              'image',
              'cover-' || n::text || '.png',
              48000,
              gen_random_uuid(),
              'image/png',
              true,
              now(), now()
       from generate_series(1, $1::int / 10) n
       on conflict do nothing`,
      [l.totalTasks]
    );

    // ---- derived counters -----------------------------------------------
    // The column is a cache the app maintains on every write; seeded rows have
    // to be brought in line or the board payload reports zeroes that the first
    // real mutation would correct.
    await run(
      'cross-project blocker counts',
      `update task
       set open_cross_project_blocker_count = counted.n
       from (
         select blocked.id,
                (select count(*)
                 from task_dependency d
                 join task blocker on blocker.id = d.blocker_task_id
                 join board_column bc on bc.id = blocker.column_id
                 where d.blocked_task_id = blocked.id
                   and blocker.project_id <> blocked.project_id
                   and blocker.archived_at is null
                   and bc.is_done = false) as n
         from task blocked
         where exists (select 1 from task_dependency d where d.blocked_task_id = blocked.id)
       ) counted
       where task.id = counted.id and task.open_cross_project_blocker_count is distinct from counted.n`
    );

    // Without this the planner works from empty-table estimates and picks plans
    // production would never pick, which makes every number below meaningless.
    await run('analyze', 'analyze');

    return benchIds(scale);
  } finally {
    await client.end();
  }
}
